// Mostly generated by https://app.quicktype.io

use chrono::{DateTime, Utc};
use serde::Deserialize;
use std::collections::HashMap;

use crate::parser::deserializer::{
    flatten_map_to_vec, flatten_map_to_vec_optional, kf_remover, map_or_vec_to_vec_optional,
    parse_chrono_date,
};

#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct CarData {
    pub entries: Vec<EntryElement>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct EntryElement {
    #[serde(deserialize_with = "parse_chrono_date")]
    pub utc: DateTime<Utc>,
    #[serde(deserialize_with = "kf_remover")]
    pub cars: HashMap<String, Car>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct Car {
    #[serde(deserialize_with = "kf_remover")]
    pub channels: HashMap<String, i64>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct Driver {
    pub racing_number: String,
    pub broadcast_name: String,
    pub full_name: String,
    pub tla: String,
    pub line: i64,
    pub team_name: String,
    pub team_colour: String,
    pub first_name: String,
    pub last_name: String,
    pub reference: String,
    pub headshot_url: Option<String>,
    pub country_code: String,
    pub name_format: Option<String>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct ExtrapolatedClock {
    #[serde(deserialize_with = "parse_chrono_date")]
    pub utc: DateTime<Utc>,
    pub remaining: String,
    pub extrapolating: Option<bool>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct Heartbeat {
    #[serde(deserialize_with = "parse_chrono_date")]
    pub utc: DateTime<Utc>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct LapCount {
    pub current_lap: Option<i64>,
    pub total_laps: Option<i64>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct Positions {
    pub position: Vec<PositionElement>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct PositionElement {
    #[serde(deserialize_with = "parse_chrono_date")]
    pub timestamp: DateTime<Utc>,
    #[serde(deserialize_with = "kf_remover")]
    pub entries: HashMap<String, EntryValue>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct EntryValue {
    pub status: DriverStatus,
    pub x: i64,
    pub y: i64,
    pub z: i64,
}

#[derive(Debug, Deserialize)]
pub enum DriverStatus {
    #[serde(rename = "OnTrack")]
    OnTrack,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct RaceControlMessages {
    #[serde(deserialize_with = "flatten_map_to_vec")]
    pub messages: Vec<RaceControlMessage>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct RaceControlMessage {
    #[serde(deserialize_with = "parse_chrono_date")]
    pub utc: DateTime<Utc>,
    pub lap: Option<i64>,
    pub category: Category,
    pub flag: Option<Flag>,
    pub scope: Option<Scope>,
    pub message: String,
    pub sector: Option<i64>,
    pub status: Option<String>,
    pub mode: Option<String>,
    pub racing_number: Option<String>,
}

#[derive(Debug, Deserialize)]
pub enum Category {
    Drs,
    Flag,
    Other,
    SafetyCar,
    CarEvent,
}

#[derive(Debug, Deserialize)]
pub enum Flag {
    #[serde(rename = "CHEQUERED")]
    Chequered,
    #[serde(rename = "CLEAR")]
    Clear,
    #[serde(rename = "DOUBLE YELLOW")]
    DoubleYellow,
    #[serde(rename = "GREEN")]
    Green,
    #[serde(rename = "YELLOW")]
    Yellow,
    #[serde(rename = "RED")]
    Red,
    #[serde(rename = "BLUE")]
    Blue,
    #[serde(rename = "BLACK AND WHITE")]
    BlackAndWhite,
}

#[derive(Debug, Deserialize)]
pub enum Scope {
    Sector,
    Track,
    Driver,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct SessionData {
    // #[serde(deserialize_with = "flatten_map_to_vec_optional")]
    pub series: Option<HashMap<String, Lap>>,
    // #[serde(deserialize_with = "flatten_map_to_vec_optional")]
    pub status_series: Option<HashMap<String, Status>>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct Lap {
    #[serde(deserialize_with = "parse_chrono_date")]
    pub utc: DateTime<Utc>,
    pub lap: Option<i64>,
    pub qualifying_part: Option<i8>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct Status {
    #[serde(deserialize_with = "parse_chrono_date")]
    pub utc: DateTime<Utc>,
    pub track_status: Option<String>,
    pub session_status: Option<String>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct SessionInfo {
    pub meeting: Meeting,
    pub archive_status: ArchiveStatus,
    pub key: i64,
    #[serde(rename = "Type")]
    pub session_info_type: String,
    pub name: String,
    pub start_date: String,
    pub end_date: String,
    pub gmt_offset: String,
    pub path: String,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct ArchiveStatus {
    pub status: String,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct Meeting {
    pub key: i64,
    pub name: String,
    pub official_name: String,
    pub location: String,
    pub country: Country,
    pub circuit: Circuit,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct Circuit {
    pub key: i64,
    pub short_name: String,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct Country {
    pub key: i64,
    pub code: String,
    pub name: String,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct TeamRadio {
    #[serde(deserialize_with = "flatten_map_to_vec")]
    pub captures: Vec<Capture>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct Capture {
    #[serde(deserialize_with = "parse_chrono_date")]
    pub utc: DateTime<Utc>,
    pub racing_number: String,
    pub path: String,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct TimingAppData {
    #[serde(deserialize_with = "kf_remover")]
    pub lines: HashMap<String, TimingAppDataLine>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct TimingAppDataLine {
    pub racing_number: Option<String>,
    pub line: Option<i64>,
    pub grid_pos: Option<String>,
    #[serde(default)]
    #[serde(deserialize_with = "map_or_vec_to_vec_optional")]
    pub stints: Option<Vec<Stint>>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct Stint {
    pub lap_time: Option<String>,
    pub lap_number: Option<i64>,
    pub lap_flags: Option<i64>,
    pub compound: Option<Compound>,
    pub new: Option<String>,
    pub tyres_not_changed: Option<String>,
    pub total_laps: Option<i64>,
    pub start_laps: Option<i64>,
}

#[derive(Debug, Deserialize)]
pub enum Compound {
    #[serde(rename = "HARD")]
    Hard,
    #[serde(rename = "MEDIUM")]
    Medium,
    #[serde(rename = "SOFT")]
    Soft,
    #[serde(rename = "INTERMEDIATE")]
    Intermediate,
    #[serde(rename = "WET")]
    Wet,
    #[serde(rename = "UNKNOWN")]
    Unknown,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct TimingData {
    pub session_part: Option<i8>,
    #[serde(deserialize_with = "kf_remover")]
    pub lines: HashMap<String, TimingDataLine>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct TimingDataLine {
    pub gap_to_leader: Option<String>,
    pub interval_to_position_ahead: Option<IntervalToPositionAhead>,
    pub line: Option<i64>,
    pub position: Option<String>,
    pub show_position: Option<bool>,
    pub racing_number: Option<String>,
    pub retired: Option<bool>,
    pub in_pit: Option<bool>,
    pub pit_out: Option<bool>,
    pub knocked_out: Option<bool>,
    pub stopped: Option<bool>,
    pub status: Option<i64>,
    pub number_of_laps: Option<i64>,
    pub number_of_pit_stops: Option<i64>,
    #[serde(default)]
    #[serde(deserialize_with = "flatten_map_to_vec_optional")]
    pub sectors: Option<Vec<Sector>>,
    pub speeds: Option<Speeds>,

    #[serde(default)]
    #[serde(deserialize_with = "flatten_map_to_vec_optional")]
    pub best_lap_times: Option<Vec<BestLapTime>>,

    pub best_lap_time: Option<BestLapTime>,
    pub last_lap_time: Option<LastLapTime>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct BestLapTime {
    pub value: String,
    pub lap: Option<i64>,
    #[serde(rename = "_deleted")]
    pub deleted: Option<Vec<String>>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct IntervalToPositionAhead {
    pub value: Option<String>,
    pub catching: Option<bool>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct LastLapTime {
    pub value: Option<String>,
    pub status: Option<i64>,
    pub overall_fastest: Option<bool>,
    pub personal_fastest: Option<bool>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct Sector {
    pub stopped: Option<bool>,
    pub previous_value: Option<String>,
    #[serde(default)]
    #[serde(deserialize_with = "flatten_map_to_vec_optional")]
    pub segments: Option<Vec<Segment>>,
    pub value: Option<String>,
    pub status: Option<i64>,
    pub overall_fastest: Option<bool>,
    pub personal_fastest: Option<bool>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct Segment {
    pub status: i64,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub struct Speeds {
    pub i1: Option<LastLapTime>,
    pub i2: Option<LastLapTime>,
    pub fl: Option<LastLapTime>,
    pub st: Option<LastLapTime>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct TimingStats {
    #[serde(deserialize_with = "kf_remover")]
    pub lines: HashMap<String, TimingStatsLine>,
    pub session_type: Option<String>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct TimingStatsLine {
    pub line: Option<i64>,
    pub racing_number: Option<String>,
    pub personal_best_lap_time: Option<PersonalBestLapTime>,
    // pub best_sectors: Option<Vec<BestSector>>,
    // pub best_speeds: Option<BestSpeeds>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct BestSector {
    pub value: String,
    pub position: Option<i64>,
    pub overall_fastest: Option<bool>,
    pub personal_fastest: Option<bool>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub struct BestSpeeds {
    pub i1: Option<BestSector>,
    pub i2: Option<BestSector>,
    pub fl: Option<BestSector>,
    pub st: Option<BestSector>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct PersonalBestLapTime {
    pub lap: Option<i64>,
    pub position: Option<i64>,
    pub value: Option<String>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct TopThree {
    #[serde(deserialize_with = "flatten_map_to_vec")]
    pub lines: Vec<LineElement>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct LineElement {
    pub position: Option<String>,
    pub show_position: Option<bool>,
    pub racing_number: Option<String>,
    pub tla: Option<String>,
    pub broadcast_name: Option<String>,
    pub full_name: Option<String>,
    pub team: Option<String>,
    pub team_colour: Option<String>,
    pub lap_time: Option<String>,
    pub lap_state: Option<i64>,
    pub diff_to_ahead: Option<String>,
    pub diff_to_leader: Option<String>,
    pub overall_fastest: Option<bool>,
    pub personal_fastest: Option<bool>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct TrackStatus {
    pub status: String,
    pub message: String,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct WeatherData {
    pub air_temp: String,
    pub humidity: String,
    pub pressure: String,
    pub rainfall: String,
    pub track_temp: String,
    pub wind_direction: String,
    pub wind_speed: String,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct TlaRcm {
    #[serde(deserialize_with = "parse_chrono_date")]
    timestamp: DateTime<Utc>,
    message: String,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct PitLaneTimeCollection {
    pub pit_times: HashMap<String, PitTimeEnum>,
}

#[derive(Debug, Deserialize)]
#[serde(untagged)]
pub enum PitTimeEnum {
    PitTime(PitTime),
    Deleted(Vec<String>),
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct PitTime {
    pub racing_number: String,
    pub duration: String,
    pub lap: String,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct LapSeries {
    pub lap_position: HashMap<String, String>,
}
